spring:
  application:
    name: tradeWorkerBackend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:TW_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: TW_schema
      hibernate.hbm2ddl.create_namespaces: true

binance:
  base-url: https://api.binance.com
  api-key: ${BINANCE_API_KEY}
  api-secret: ${BINANCE_API_SECRET}
